name: cominiapp
description: CominiApp - MVP inicial escalable con Flutter + Firebase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1

  # Estado
  flutter_riverpod: ^2.5.1

  # Utilidades
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.2

  # GPS y permisos
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
